"use client";
import { useEffect, useState } from "react";

type Identity = { seedId: string; key: CryptoKeyPair; manifestHash: string; homeUrl: string; generation: number; publicRaw: ArrayBuffer };
const encoder = new TextEncoder();
const toB64 = (b: ArrayBuffer) => btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const fromB64 = (s: string) => Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")), c => c.charCodeAt(0));
const uuidv7 = () => { const b=crypto.getRandomValues(new Uint8Array(16)), t=BigInt(Date.now()); for(let i=5;i>=0;i--) b[i]=Number((t>>BigInt((5-i)*8))&255n); b[6]=(b[6]&15)|112; b[8]=(b[8]&63)|128; return [...b].map(x=>x.toString(16).padStart(2,"0")).join("").replace(/(.{8})(.{4})(.{4})(.{4})(.{12})/,"$1-$2-$3-$4-$5"); };
const message=(kind:string,i:Identity,nonce:string,body="")=>`leis-seed-sync/v1|${kind}|${i.seedId}|${i.generation}|${i.manifestHash}|${toB64((i as any).publicRaw)}|${nonce}|${body}`;
const identityStore = (mode:"get"|"set", value?:Identity) => new Promise<Identity|null>((resolve,reject)=>{ const open=indexedDB.open("leis-sync-client",1); open.onupgradeneeded=()=>open.result.createObjectStore("identity"); open.onerror=()=>reject(open.error); open.onsuccess=()=>{const tx=open.result.transaction("identity",mode==="get"?"readonly":"readwrite"), store=tx.objectStore("identity"); const request=mode==="get"?store.get("default"):store.put(value,"default"); request.onsuccess=()=>resolve(mode==="get"?(request.result??null):value??null); request.onerror=()=>reject(request.error);};});

export default function SyncClient() {
 const [identity,setIdentity]=useState<Identity|null>(null),[topics,setTopics]=useState("LEIS"),[delta,setDelta]=useState(""),[status,setStatus]=useState("Choose the LEIS Manifest to begin.");
 useEffect(()=>{ void identityStore("get").then(saved=>{if(saved){setIdentity(saved);setStatus(`Local Seed restored: ${saved.seedId}`);}}).catch(()=>undefined);},[]);
 const activate=async(file:File)=>{ try { const manifest=JSON.parse(await file.text()), home=manifest?.home?.url; if(!home?.startsWith("https://")) throw Error("This is not a compatible LEIS Manifest."); const hash=toB64(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(manifest)))); const key=await crypto.subtle.generateKey({name:"Ed25519"},true,["sign","verify"]) as CryptoKeyPair; const publicRaw=await crypto.subtle.exportKey("raw",key.publicKey); const i:Identity={seedId:uuidv7(),key,manifestHash:hash,homeUrl:home,generation:1,publicRaw}; await identityStore("set",i); setIdentity(i); setStatus("Local Seed identity created and stored on this device. Register it when you are ready."); } catch(e){setStatus(e instanceof Error?e.message:"Could not read Manifest.");} };
 const signed=async(kind:string,i:Identity,nonce:string,body="")=>toB64(await crypto.subtle.sign({name:"Ed25519"},i.key.privateKey,encoder.encode(message(kind,i,nonce,body))));
 const register=async()=>{ if(!identity)return; try { const api=identity.homeUrl.replace(/\/$/,"")+"/api/seed-sync/v1"; const challenge=await (await fetch(api+"/challenge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({protocol:"leis-seed-sync/v1",purpose:"register"})})).json(); const publicKey=toB64((identity as any).publicRaw); const signature=await signed("register",identity,challenge.nonce); const r=await fetch(api+"/seeds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({protocol:"leis-seed-sync/v1",seed_id:identity.seedId,generation:1,manifest_hash:identity.manifestHash,public_key:publicKey,home_url:identity.homeUrl,topics:topics.split(",").map(x=>x.trim()).filter(Boolean),nonce:challenge.nonce,signature})}); const out=await r.json(); setStatus(r.ok?`Seed verified: ${out.seed_id}`:out.error); }catch(e){setStatus(e instanceof Error?e.message:"Registration failed.");} };
 const submit=async()=>{ if(!identity||!delta.trim())return; try { const api=identity.homeUrl.replace(/\/$/,"")+"/api/seed-sync/v1", publicKey=toB64((identity as any).publicRaw), topic=topics.split(",")[0].trim()||"LEIS", type="question"; const c=await (await fetch(api+"/challenge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({protocol:"leis-seed-sync/v1",purpose:"delta"})})).json(); const signature=await signed("delta",identity,c.nonce,`${type}|${topic}|${delta.trim()}`); const r=await fetch(api+"/deltas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({protocol:"leis-seed-sync/v1",seed_id:identity.seedId,generation:1,manifest_hash:identity.manifestHash,public_key:publicKey,nonce:c.nonce,signature,topic,type,delta:delta.trim()})}); const out=await r.json(); setStatus(r.ok?"Public Delta verified and shared with Topic Fabric.":out.error); }catch(e){setStatus(e instanceof Error?e.message:"Delta failed.");} };
 return <main style={{maxWidth:760,margin:"auto",padding:"64px 24px",lineHeight:1.55}}><p style={{color:"#83edf4",letterSpacing:2,fontSize:12}}>LEIS SYNC CLIENT V1</p><h1>Start a public LEIS Seed.</h1><p>This client creates a local Seed identity and sends only public metadata or a public Delta. It never reads your AI chat, files, email or name.</p><label>1. Choose the Root Manifest <input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&activate(e.target.files[0])}/></label><p><label>2. Public topics <input value={topics} onChange={e=>setTopics(e.target.value)} /></label></p><button onClick={register} disabled={!identity}>3. Register this Seed</button><hr/><label>4. Public Delta <textarea value={delta} onChange={e=>setDelta(e.target.value)} placeholder="Can activation be measured?" /></label><p><button onClick={submit} disabled={!identity||!delta.trim()}>Send public Delta</button></p><p aria-live="polite"><b>Status:</b> {status}</p></main>;
}
