import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import './navigation.css';

const topics={'LEIS principles':['lineage','reconstruction','validation','orientation','reality','seed'],'Artificial intelligence':['ai','claude','prompt','automation','agent','machine learning'],'Technology & systems':['software','system','engineering','cyber','data','sql'],'Leadership & organisation':['leadership','management','teams','business','decision'],'Health & mind':['psychiatry','brain','health','clinical','immunity','medicine'],'History & society':['history','rome','korea','politics','society','geopolitics'],'Media archive':['video','image','book','audio','document','plaud']};
const screens={
 '/timeline':{eyebrow:'LEIS / RECONSTRUCTION TIMELINE',title:'Understanding in motion.',intro:'A living orientation map. Each point identifies whether it is documented evidence, creator-reported context or a human time marker.',cards:[['DOCUMENTED','9 July 2026 \u00b7 First constitutional seed','The earliest currently located constitutional evidence identifies Martin Pu\u017e\u00edk as Founder and Initial Architect, and already records mission, preservation, seed, lineage, uncertainty and technology-independence.'],['CREATOR-REPORTED','Around 10 July 2026 \u00b7 LEIS core completed','Martin Pu\u017e\u00edk reports completing the LEIS core independently during an intensive five-day period. Copilot was a working carrier and AI underlayer, not the author.'],['CONTEXT MARKER','14 July 2026 \u00b7 Personal timeline anchor','A family visit in Prague provides a human time marker shortly after the core was completed.'],['EVOLUTION','After the seed \u00b7 Technical collaboration','Martin introduced the seed to M.A.J. Pu\u017e\u00edk. His technical and AI experience supported practical activation and development while the LEIS core retained its independent origin.'],['PRESENT','Reconstruction phase','MEDIA and LEIS archive work preserves original sources, SHA-256 lineage, recovery gaps and portals that make evidence navigable.']]},
 '/pavla':{eyebrow:'LEIS / QUICK ORIENTATION',title:'LEIS in two minutes.',intro:'A concise, source-aware starting point for anyone: what LEIS is, where it came from and how its value can be tested.',cards:[['ORIGIN','The story in one minute','Martin Pu\u017e\u00edk created the LEIS core independently during an intensive five-day period at home. Copilot was a working carrier and AI underlayer, not the author. Later, M.A.J. Pu\u017e\u00edk\u2019s technical and AI experience supported practical use and development.'],['DISTINCTION','What LEIS is \u2014 and is not','LEIS is not an AI model, plugin or software product. It is a technology-independent way to organise orientation, evidence, validation and continuity of understanding.'],['TEST','Why it may matter','The relevant question is whether a new person can reconstruct reasons behind a decision more quickly and reliably than with ordinary documentation alone.'],['VOICE','In the creator\u2019s words','Reality was never hidden. Recognition was incomplete. The goal is not to accumulate more knowledge; it is to activate the right understanding at the right moment. Reality remains the final validator.'],['MEDIA','For journalists','The useful story angle is not unverified technical superiority. It is how a human-created, reality-oriented framework tries to make sources, uncertainty and decision context survive transfer between people and technologies.']]}
};

function App(){
 const [path,setPath]=useState(location.pathname),[query,setQuery]=useState(''),[topic,setTopic]=useState(''),[results,setResults]=useState([]),[status,setStatus]=useState('Choose a topic or enter a question.');
 useEffect(()=>{const back=()=>setPath(location.pathname);addEventListener('popstate',back);return()=>removeEventListener('popstate',back)},[]);
 const navigate=to=>{history.pushState({},'',to);setPath(to);scrollTo({top:0,behavior:'smooth'})};
 const perform=async(q=query,t=topic)=>{if(!q&&!t)return;setStatus('LEIS logic: collecting signals and checking source lineage\u2026');const response=await fetch(`/api/search?q=${encodeURIComponent(q)}&topic=${encodeURIComponent(t)}`),data=await response.json();setResults(data.results);setStatus(`${data.count} relevant source(s). Each result remains traceable to its PDF.`)};
 const nav=<nav className="nav-ring" aria-label="LEIS navigation"><button className={path==='/'?'chosen':''} onClick={()=>navigate('/')}><i>{'\u03a9'}</i><span>Media Portal</span></button><button className={path==='/timeline'?'chosen':''} onClick={()=>navigate('/timeline')}><i>{'\u25cc'}</i><span>Timeline</span></button><button className={path==='/pavla'?'chosen':''} onClick={()=>navigate('/pavla')}><i>{'\u2726'}</i><span>Quick Orientation</span></button></nav>;
 const screen=screens[path];
 if(screen)return <main className="detail">{nav}<div className="eyebrow">{screen.eyebrow}</div><h1>{screen.title}</h1><p className="intro">{screen.intro}</p><div className="sequence">{screen.cards.map(([tag,title,text],i)=><article className="detail-card" style={{'--delay':`${i*70}ms`}} key={title}><span>{tag}</span><h2>{title}</h2><p>{text}</p></article>)}</div>{nav}</main>;
 return <div className="shell"><aside><button className="omega-link" onClick={()=>navigate('/')} aria-label="Return to Media Portal"><img src="/omega.png"/></button><b>LEIS</b><p>Reality-oriented understanding<br/>Preserve. Validate. Reconstruct.</p><div className="creator"><strong>{'Creator: Martin Pu\u017e\u00edk'}</strong>{'Visionary \u00b7 Constitution author'}<br/>{'Founder of LEIS \u00b7 Ethical framework'}<hr/><strong>{'M.A.J. Pu\u017e\u00edk'}</strong>{'Technical collaborator'}<br/>{'AI and technology expertise \u00b7 Practical activation and technical development'}</div><label>TOPICS / IDEAS</label>{Object.keys(topics).map(name=><button className={topic===name?'active':''} key={name} onClick={()=>{setTopic(name);setQuery(name);perform(name,name)}}>{name}</button>)}</aside><main>{nav}<div className="eyebrow">MEDIA INTELLIGENCE PORTAL</div><h1>Find context,<br/>not only files.</h1><p className="intro">LEIS search connects signals in the catalog, keeps every result tied to source lineage and makes uncertainty visible instead of hiding it.</p><div className="loop">{'REALITY \u2192 SIGNALS \u2192 PATTERNS \u2192 RECOGNITION \u2192 VALIDATION \u2192 LINEAGE \u2192 ORIENTATION'}</div><form onSubmit={e=>{e.preventDefault();perform()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search books, authors, topics, names, principles\u2026'}/><button>LEIS SEARCH</button></form><section className="gateways"><button className="gateway timeline" onClick={()=>navigate('/timeline')}><i>{'\u25cc'}</i><h2>Living LEIS timeline</h2><p>Follow the documented seed, creator-reported completion and reconstruction.</p><strong>{'Explore the timeline \u2192'}</strong></button><button className="gateway orientation" onClick={()=>navigate('/pavla')}><i>{'\u2726'}</i><h2>LEIS Quick Orientation</h2><p>A human two-minute start: what it is, why it matters and how to test it.</p><strong>{'Start the orientation \u2192'}</strong></button></section><p className="status">{status}</p><section>{results.map(item=><article className="result" key={item.path}><a href={`/open?path=${encodeURIComponent(item.path)}`}>{item.name}</a><small>{`${item.size.toLocaleString()} B \u00b7 ${item.path}`}</small><div>{item.signals.map(signal=><em key={signal}>{signal}</em>)}</div><p>{item.snippet||'Match in source filename.'}</p></article>)}</section></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
