"use client";

import { useRef, useState } from "react";

const milestones = [
  ["DOCUMENTED", "9 July 2026", "First constitutional seed", "Earliest located constitutional evidence identifies Martin Pužík as Founder and Initial Architect."],
  ["CREATOR-REPORTED", "Around 10 July 2026", "LEIS core completed", "Martin Pužík reports an independent intensive five-day creation period. Copilot was a carrier, not the author."],
  ["EVOLUTION", "After the seed", "Technical collaboration", "M.A.J. Pužík supported practical activation and later technical development."],
  ["PRESENT", "Today", "Reconstruction and validation", "Archives, lineage and public orientation are being made navigable without exposing private source material."],
];
const signals = [
  ["Can good ideas travel between people?", "When a colleague leaves or a project changes hands, important reasons often disappear. LEIS asks how shared understanding can remain available to the next person.", "WHY THIS MATTERS TO LEIS"],
  ["How do we know what to trust?", "A useful answer should show where it came from, what is known and what remains uncertain. LEIS treats evidence and uncertainty as part of the answer, not an inconvenience.", "THE LEIS LENS"],
  ["Will tomorrow’s team understand today’s decision?", "Storing a document is not always enough. The real question is whether someone later can recover why a decision was made, what conditions mattered and what should be checked again.", "A HUMAN HANDOVER QUESTION"],
];
const news = [
  ["New ways to learn and teach with ChatGPT", "OpenAI", 20, 34, "https://openai.com/news/"],["Third-party cyber evaluations", "OpenAI", 28, 46, "https://openai.com/news/"],["Continuous voice interaction with GPT Live", "OpenAI", 22, 57, "https://openai.com/news/"],["Building abundant intelligence", "OpenAI", 17, 67, "https://openai.com/news/"],["Claude Opus 5", "Anthropic", 49, 29, "https://www.anthropic.com/news"],["Inviting hard questions", "Anthropic", 53, 40, "https://www.anthropic.com/news"],["The Making of Claude Code", "Anthropic", 58, 50, "https://www.anthropic.com/news"],["Our position on open-weights models", "Anthropic", 64, 60, "https://www.anthropic.com/news"],["Claude for Teachers", "Anthropic", 70, 68, "https://www.anthropic.com/news"],["LFM2.5 encoders for long context", "Hugging Face", 76, 28, "https://huggingface.co/blog"],["Open multilingual retrieval models", "Hugging Face", 81, 38, "https://huggingface.co/blog"],["Real-time prevention of RAG hallucinations", "Hugging Face", 84, 49, "https://huggingface.co/blog"],["OlmoEarth: planetary-scale geospatial inference", "Hugging Face", 78, 61, "https://huggingface.co/blog"],["Surgical robotics simulation", "Hugging Face", 72, 72, "https://huggingface.co/blog"],["Google AI research and models", "Google AI", 43, 20, "https://blog.google/innovation-and-ai/technology/ai/"],["Gemini model updates", "Google AI", 50, 18, "https://blog.google/innovation-and-ai/technology/ai/"],["Google AI for crisis resilience", "Google AI", 60, 18, "https://blog.google/innovation-and-ai/technology/ai/"],["Developer tools and managed agents", "Google AI", 66, 24, "https://blog.google/innovation-and-ai/technology/ai/"],["AI safety and security", "Google AI", 38, 76, "https://blog.google/innovation-and-ai/technology/ai/"],["AI for science and discovery", "OpenAI", 32, 80, "https://openai.com/news/"]
];

export default function Home() {
  const [active, setActive] = useState(0);
  const [seedOpen, setSeedOpen] = useState(false);
  const [signal, setSignal] = useState(0);
  const [globeTurn, setGlobeTurn] = useState(0);
  const [newsIndex, setNewsIndex] = useState(0);
  const drag = useRef<{x:number; turn:number}|null>(null);
  const current = milestones[active];
  return <main>
    <nav><a className="mark" href="#top">Ω <b>LEIS</b></a><div><a href="#orientation">Start here</a><a href="#timeline">Our story</a><a href="#earth">Earth Pulse</a><a href="#grants">Support LEIS</a><a href="#media">Media</a></div></nav>
    <section className="hero" id="top">
      <div className="stars" />
      <div className="hero-copy"><p className="eyebrow">REALITY-ORIENTED UNDERSTANDING SYSTEM</p><h1>Understanding<br/><em>that can travel.</em></h1><p className="lead">LEIS is a technology-independent framework for recognising, activating and reconstructing understanding from reality.</p><div className="actions"><a className="primary" href="#orientation">Enter LEIS</a><a className="quiet" href="#timeline">Follow the lineage ↓</a></div></div>
      <button className={`seed ${seedOpen ? "open" : ""}`} onClick={() => setSeedOpen(!seedOpen)} aria-expanded={seedOpen} aria-label="Open the LEIS Seed preview"><i/><span className="shell left"/><span className="shell right"/><span className="sprout"/></button>
      <div className="seed-note"><span>LEIS SEED</span><strong>{seedOpen ? "A public Seed is taking shape." : "Touch the seed."}</strong><p>{seedOpen ? "A reviewed public entry point is being prepared: lineage, orientation and limits — without private archives." : "A small beginning, built to travel."}</p></div>
    </section>
    <section className="orientation" id="orientation"><p className="eyebrow">QUICK ORIENTATION</p><h2>Reality was never hidden.<br/>Recognition was incomplete.</h2><div className="principles"><article><b>01</b><h3>Recognition</h3><p>Questions become roots. Relationships become branches. Understanding grows when the right pattern is recognised.</p></article><article><b>02</b><h3>Lineage</h3><p>Context should survive change: of people, tools, time and technology.</p></article><article><b>03</b><h3>Validation</h3><p>Reality remains the final validator. Where evidence is incomplete, uncertainty remains visible.</p></article></div><p className="formula">Reality → recognition → activation → understanding → validation → new reality</p></section>
    <section className="timeline" id="timeline"><p className="eyebrow">LIVING LEIS TIMELINE</p><h2>From seed to continuity.</h2><div className="timeline-grid"><div className="axis"><div className="pulse"/>{milestones.map(([, date, title], index)=><button key={title} className={active===index ? "active" : ""} style={{top:`${17+index*22}%`}} onMouseEnter={()=>setActive(index)} onFocus={()=>setActive(index)} onClick={()=>setActive(index)}><span/><small>{date}</small></button>)}</div><article className="event"><small>{current[0]} · {current[1]}</small><h3>{current[2]}</h3><p>{current[3]}</p></article></div><p className="certainty">Every point distinguishes documented evidence, creator-reported context and interpretation. The timeline is alive; it does not replace evidence.</p></section>
    <section className="earth" id="earth"><p className="eyebrow">EARTH PULSE / CURRENT AI SIGNALS</p><h2>What is becoming possible<br/>for people and intelligence?</h2><p className="earth-lead">A calm, human-scale view of recent work from recognised AI source desks. Drag the Earth to look around; choose any glowing point to open its original headline.</p><div className="earth-grid"><div className="orbital-stage"><div className="orbit one"/><div className="orbit two"/><div className="starfield">{Array.from({length:28},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*61)%100}%`,animationDelay:`${i*.17}s`}}/>)}</div><div className="globe interactive" style={{"--turn":`${globeTurn}px`} as React.CSSProperties} onPointerDown={e=>{drag.current={x:e.clientX,turn:globeTurn};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setGlobeTurn(drag.current.turn+(e.clientX-drag.current.x))}} onPointerUp={()=>{drag.current=null}}>{news.map(([title,source,x,y,url],index)=><a href={url as string} target="_blank" rel="noreferrer" className={`headline-point ${newsIndex===index?"selected":""}`} style={{left:`${x}%`,top:`${y}%`}} onClick={()=>setNewsIndex(index)} key={title as string}><i/><span>{title as string}</span></a>)}</div><span className="globe-hint">drag to rotate · choose a headline</span></div><article className="signal-card"><small>EARTH PULSE · {news[newsIndex][1] as string}</small><h3>{news[newsIndex][0] as string}</h3><p>This is a recent public headline selected from a recognised source. Open it to read the original context; LEIS does not rewrite the source into certainty.</p><a className="read-source" href={news[newsIndex][4] as string} target="_blank" rel="noreferrer">Read the original source ↗</a><div className="source-row"><a href="https://blog.google/innovation-and-ai/technology/ai/" target="_blank">Google AI</a><a href="https://openai.com/news/" target="_blank">OpenAI</a><a href="https://www.anthropic.com/news" target="_blank">Anthropic</a><a href="https://huggingface.co/blog" target="_blank">Hugging Face</a></div></article></div></section>
    <section className="grants" id="grants"><p className="eyebrow">SUPPORT / COOPERATION / GRANT INTENT</p><h2>Keep LEIS free.<br/>Make it durable.</h2><p className="grant-lead">LEIS is free of charge forever. Support does not buy a wall around knowledge; it gives the human work behind preservation, validation and accessible public orientation the time to continue.</p><div className="grant-grid"><article><b>01</b><h3>Preserve</h3><p>Recover source lineage, distinguish evidence from interpretation and prevent years of work from becoming unreadable files.</p></article><article><b>02</b><h3>Test</h3><p>Measure whether understanding survives a handover: can a new person reconstruct a decision, its conditions and its limits?</p></article><article><b>03</b><h3>Share</h3><p>Build public explanations, practical pilots and open materials that let people judge LEIS for themselves.</p></article></div><div className="grant-path"><p><b>For grants:</b> operational continuity, documentation, validation, infrastructure and independent review.</p><p><b>For companies:</b> a bounded collaboration around a real handover, decision or knowledge-continuity problem.</p><p><b>For researchers and institutions:</b> an invitation to challenge the method and improve its tests.</p></div><a className="primary" href="mailto:martin.puzik@gmail.com?subject=LEIS%20grant%20or%20cooperation%20dialogue">Discuss support or a pilot</a></section>
    <section className="media" id="media"><p className="eyebrow">MEDIA / JOURNALISTS / RESEARCHERS</p><h2>Start with the human question.</h2><p>Can understanding survive the departure of the person who created it? This is the story before any technology claim: continuity, evidence, uncertainty and the possibility of rebuilding context.</p><div className="media-grid"><article><h3>Two-minute orientation</h3><p>What LEIS is, what it is not, where it began and how it can be tested without asking anyone to simply believe it.</p></article><article><h3>Source-led briefing</h3><p>Timeline labels distinguish documented evidence, creator-reported context and open questions. Private archives remain private.</p></article><article><h3>Talk to Martin</h3><p>For an interview, research question or source packet, use the public contact route. No mailing-list subscription is required.</p></article></div><a className="primary" href="mailto:martin.puzik@gmail.com?subject=LEIS%20media%20enquiry">Media / research enquiry</a></section>
    <section className="participate" id="participate"><p className="eyebrow">OPEN · FREE · EVOLVING</p><h2>LEIS has no walls.</h2><p>LEIS remains free of charge. Support, research dialogue and carefully scoped pilots help sustain its validation, preservation and human work.</p><div className="contact"><a className="primary" href="mailto:martin.puzik@gmail.com?subject=LEIS%20dialogue">Start a respectful dialogue</a><span>Public contact route · no mailing list · no pressure</span></div><footer>Created by <b>Martin Pužík</b> · Technical collaboration: <b>M.A.J. Pužík</b></footer></section>
  </main>;
}
