import test from "node:test";
import assert from "node:assert/strict";
import { webcrypto } from "node:crypto";

const crypto = webcrypto;
const base = process.env.LEIS_SYNC_BASE ?? "https://leis-understanding-system.puzik.chatgpt.site";
const protocol = "leis-seed-sync/v1";
const b64 = bytes => Buffer.from(bytes).toString("base64url");
const uuidv7 = () => { const b = crypto.getRandomValues(new Uint8Array(16)), time = BigInt(Date.now()); for (let i = 5; i >= 0; i--) b[i] = Number((time >> BigInt((5 - i) * 8)) & 255n); b[6] = (b[6] & 15) | 112; b[8] = (b[8] & 63) | 128; const h = Buffer.from(b).toString("hex"); return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`; };
const request = async (path, body) => { const r = await fetch(base + path, { method: body ? "POST" : "GET", headers: body ? { "content-type": "application/json" } : {}, body: body && JSON.stringify(body) }); return { status: r.status, body: await r.json() }; };
async function seed(label) { const pair = await crypto.subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]); const publicKey = b64(await crypto.subtle.exportKey("raw", pair.publicKey)); const seedId = uuidv7(); const manifestHash = Buffer.from(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(`LEIS validation ${label}`))).toString("hex"); const challenge = await request("/api/seed-sync/v1/challenge", { protocol, purpose: "register" }); assert.equal(challenge.status, 200); const message = `${protocol}|register|${seedId}|1|${manifestHash}|${publicKey}|${challenge.body.nonce}|`; const signature = b64(await crypto.subtle.sign({ name: "Ed25519" }, pair.privateKey, new TextEncoder().encode(message))); const registration = await request("/api/seed-sync/v1/seeds", { protocol, seed_id: seedId, generation: 1, manifest_hash: manifestHash, public_key: publicKey, home_url: base, topics: ["LEIS Validation"], nonce: challenge.body.nonce, signature }); assert.equal(registration.status, 201); assert.equal(registration.body.status, "verified"); return { pair, publicKey, seedId, manifestHash }; }
test("LEIS Seed Network V1 reality validation", async () => { const a = await seed("A"), b = await seed("B"); assert.notEqual(a.seedId, b.seedId); assert.match(a.seedId, /^[0-9a-f]{8}-/i); const challenge = await request("/api/seed-sync/v1/challenge", { protocol, purpose: "delta" }); const topic = "LEIS Validation", delta = `Automated validation ${a.seedId}`, type = "question"; const message = `${protocol}|delta|${a.seedId}|1|${a.manifestHash}|${a.publicKey}|${challenge.body.nonce}|${type}|${topic}|${delta}`; const signature = b64(await crypto.subtle.sign({ name: "Ed25519" }, a.pair.privateKey, new TextEncoder().encode(message))); const sent = await request("/api/seed-sync/v1/deltas", { protocol, seed_id: a.seedId, generation: 1, manifest_hash: a.manifestHash, public_key: a.publicKey, nonce: challenge.body.nonce, signature, topic, type, delta }); assert.equal(sent.status, 201); const fabric = await request("/api/seed-sync/v1/topic-fabric"); assert.ok(fabric.body.deltas.some(item => item.seed_id === a.seedId && item.topic === topic)); const state = await request(`/api/seed-sync/v1/seeds/${b.seedId}/state`); assert.equal(state.body.seed.status, "verified"); const metrics = await request("/api/seed-sync/v1"); assert.ok(metrics.body.seed_farm.total_seeds >= 2); assert.ok(metrics.body.seed_farm.active_seeds >= 2); assert.ok(metrics.body.seed_farm.delta_growth.total >= 1); });
